name: Node.js CI Workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
permissions:  
  contents: read
  security-events: write
  
jobs:
  test:
    uses: Agnaldo-Cavaleiro/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      artifact-name: 'dist'
      artifact-path: 'dist'
      node_version:  '18.x'
